# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("logger.proto", :syntax => :proto3) do
    add_message "logger.Result" do
      optional :success, :bool, 1
      optional :length, :int64, 2
    end
    add_message "logger.SimpleText" do
      optional :text, :string, 1
    end
  end
end

module Logger
  Result = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logger.Result").msgclass
  SimpleText = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logger.SimpleText").msgclass
end
